name: mkg-jbi
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy
  - pandas
  - scipy
  - scikit-learn
  - matplotlib
  - lifelines
  - scikit-survival
  - pytorch
  - pip
  - pip:
      - GEOparse
      - pycox
      - torchtuples
      - xgboost

